name: Keep app awake

on:
  schedule:
    - cron: '*/14 * * * *'  # Cada 14 minutos
  workflow_dispatch:        # 👈 Esto permite lanzarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a la app
        run: curl -s https://url-temp-link.onrender.com/ > /dev/null
