name: Keep app awake

on:
  schedule:
    - cron: '*/14 * * * *'  # Cada 14 minutos
  workflow_dispatch:        # Permite ejecutar manualmente desde GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Realistic ping to keep Render awake
        run: curl -L --max-time 10 https://url-temp-link.onrender.com/
